apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rapid-tern-go 
  janus-idp.io/tekton: rapid-tern-go
  backstage.io/kubernetes-id: rapid-tern-go
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: rapid-tern-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  